# Generated by Django 2.1.5 on 2019-02-27 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userpost',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.PROTECT, to='app.UserInfo'),
        ),
    ]
