# Generated by Django 2.1.5 on 2019-02-28 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190227_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.UserInfo'),
        ),
    ]
