# Generated by Django 2.1.5 on 2019-02-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190228_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.UserInfo'),
        ),
    ]
