# Generated by Django 2.1.5 on 2019-03-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
