# Generated by Django 2.1.5 on 2019-03-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190306_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uservote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='app.Publish'),
        ),
    ]
